language: ruby
rvm:
  - 1.9.3
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
before_install:
  - sudo apt-get update
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle install
script: "ruby -e 'system(\"jasmine-headless-webkit\")'"
notifications:
  email:
    - "kas@ncgr.org"
