language: ruby
rvm:
  - 1.9.3
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
env:
  - DB=mysql
before_install:
  - sudo apt-get update
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle install
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database lis_sequence_search_test;'; fi"
script: "rake travis:spec"
notifications:
    email:
        - "kas@ncgr.org"
