## Quorum Settings ##
#
# DO NOT edit this file directly. To configure Quorum edit
# config/quorum_settings.yml.

## Load Quorum Setttings ##
settings = YAML.load_file(
  "#{::Rails.root.to_s}/config/quorum_settings.yml"
)[::Rails.env.to_s]

## Sub %{RAILS_ROOT} ##
settings.keys.each do |k|
  settings[k.to_s].each_value do |v|
    if v.kind_of?(String)
      v.to_s.gsub!('%{RAILS_ROOT}', ::Rails.root.to_s)
    end
  end
end

blast = settings['blast']

## Quorum Blast Settings ##
Quorum.blast_remote      = blast['remote']
Quorum.blast_ssh_host    = blast['ssh_host']
Quorum.blast_ssh_user    = blast['ssh_user']
Quorum.blast_ssh_options = blast['ssh_options']
Quorum.blast_bin         = blast['bin']
Quorum.blast_log_dir     = blast['log_dir']
Quorum.blast_tmp_dir     = blast['tmp_dir']
Quorum.blast_db          = blast['blast_db']
Quorum.tblastn           = blast['tblastn']
Quorum.blastp            = blast['blastp']
Quorum.blastn            = blast['blastn']
Quorum.blastx            = blast['blastx']
Quorum.blast_threads     = blast['blast_threads']

